### ISSUE TITLE
readme.md not up to date?

### ISSUE THREAD

**Issue by SayChi** [24hoursmedia-craftcms/comments-work#11]
The readme.md is incomplete/wrong it seems. For example the link to the quick start guide does not work and `commentsWork.fetchComments(entry, 0, 5)` (which is in the readme) seems to be incorrect. (I had to use craft.commentsWork.services.fetchComments instead)

This makes it difficult to use this plugin, and probably scares away new users. I did just spot on [your docs pages](https://io.24hoursmedia.com/comments-work/show-comment-entries-on-a-page) that craft.commentsWork.services is indeed the way to go, but it might help to show this in the readme.md and on the first page of your docs too (because the current code that is showing there will throw errors)

**Comment by 24hoursmedia-craftcms** [comment]
@SayChi Thank you, I'll update the docs asap.
