### ISSUE TITLE
Not instantiable – yii\di\NotInstantiableException

### ISSUE THREAD

**Issue by axelhebenstreit** [24hoursmedia-craftcms/comments-work#14]
I would like to report the following issue with Comments Work (https://plugins.craftcms.com/comments-work):

just installed comments Work under craft 3.6.2 and i got this

Not instantiable – yii\di\NotInstantiableException

Failed to instantiate component or class "twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset".
↵
Caused by: ReflectionException

Class twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset does not exist

in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php at line 508

ReflectionException: Class twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset does not exist in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php:508
Stack trace:
#0 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(508): ReflectionClass->__construct('twentyfourhours...')
#1 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('twentyfourhours...')
#2 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('twentyfourhours...', Array, Array)
#3 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('twentyfourhours...', Array, Array)
#4 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
#5 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('twentyfourhours...', Array, true)
#6 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('twentyfourhours...')
#7 /srv/users/craft/apps/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('twentyfourhours...')
#8 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#9 /srv/users/craft/apps/craft/storage/runtime/compiled_templates/db/dbbf2adde7351591045c2d18b3c4c383f1351fc842f470704cdcaf665d945ddd.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#10 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8c7b61297d009dd5f97c71a175c31de23ec89891531a3c93d4929e73d239ca3e->doDisplay(Array, Array)
#11 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /srv/users/craft/apps/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /srv/users/craft/apps/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('comments-work/s...', Array)
#16 /srv/users/craft/apps/craft/vendor/twentyfourhoursmedia/comments-work/src/CommentsWork.php(205): craft\web\View->renderTemplate('comments-work/s...', Array)
#17 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/base/Plugin.php(217): twentyfourhoursmedia\commentswork\CommentsWork->settingsHtml()
#18 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#19 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('comments-work', Object(twentyfourhoursmedia\commentswork\CommentsWork))
#20 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#22 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
#23 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
#24 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
#25 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
#26 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#27 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /srv/users/craft/apps/craft/public/index.php(22): yii\base\Application->run()
#29 {main}

Next yii\di\NotInstantiableException: Failed to instantiate component or class "twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset". in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php:510
Stack trace:
#0 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('twentyfourhours...')
#1 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('twentyfourhours...', Array, Array)
#2 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('twentyfourhours...', Array, Array)
#3 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
#4 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('twentyfourhours...', Array, true)
#5 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('twentyfourhours...')
#6 /srv/users/craft/apps/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('twentyfourhours...')
#7 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#8 /srv/users/craft/apps/craft/storage/runtime/compiled_templates/db/dbbf2adde7351591045c2d18b3c4c383f1351fc842f470704cdcaf665d945ddd.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#9 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8c7b61297d009dd5f97c71a175c31de23ec89891531a3c93d4929e73d239ca3e->doDisplay(Array, Array)
#10 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#12 /srv/users/craft/apps/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /srv/users/craft/apps/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('comments-work/s...', Array)
#15 /srv/users/craft/apps/craft/vendor/twentyfourhoursmedia/comments-work/src/CommentsWork.php(205): craft\web\View->renderTemplate('comments-work/s...', Array)
#16 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/base/Plugin.php(217): twentyfourhoursmedia\commentswork\CommentsWork->settingsHtml()
#17 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#18 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('comments-work', Object(twentyfourhoursmedia\commentswork\CommentsWork))
#19 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#21 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
#22 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
#23 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
#24 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
#25 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#26 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /srv/users/craft/apps/craft/public/index.php(22): yii\base\Application->run()
#28 {main}

**Comment by 24hoursmedia-craftcms** [comment]
Should be fixed by now

**Comment by axelhebenstreit** [comment]
> Should be fixed by now
> 

I’m afraid not – just updated to 1.2.1 and i get this:


ReflectionException: Class twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset does not exist in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php:508
Stack trace:
#0 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(508): ReflectionClass->__construct('twentyfourhours...')
#1 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('twentyfourhours...')
#2 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('twentyfourhours...', Array, Array)
#3 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('twentyfourhours...', Array, Array)
#4 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
#5 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('twentyfourhours...', Array, true)
#6 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('twentyfourhours...')
#7 /srv/users/craft/apps/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('twentyfourhours...')
#8 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#9 /srv/users/craft/apps/craft/storage/runtime/compiled_templates/db/dbbf2adde7351591045c2d18b3c4c383f1351fc842f470704cdcaf665d945ddd.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#10 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8c7b61297d009dd5f97c71a175c31de23ec89891531a3c93d4929e73d239ca3e->doDisplay(Array, Array)
#11 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /srv/users/craft/apps/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /srv/users/craft/apps/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('comments-work/s...', Array)
#16 /srv/users/craft/apps/craft/vendor/twentyfourhoursmedia/comments-work/src/CommentsWork.php(205): craft\web\View->renderTemplate('comments-work/s...', Array)
#17 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/base/Plugin.php(217): twentyfourhoursmedia\commentswork\CommentsWork->settingsHtml()
#18 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#19 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('comments-work', Object(twentyfourhoursmedia\commentswork\CommentsWork))
#20 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#22 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
#23 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
#24 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
#25 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
#26 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#27 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /srv/users/craft/apps/craft/public/index.php(22): yii\base\Application->run()
#29 {main}

Next yii\di\NotInstantiableException: Failed to instantiate component or class "twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset". in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php:510
Stack trace:
#0 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('twentyfourhours...')
#1 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('twentyfourhours...', Array, Array)
#2 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('twentyfourhours...', Array, Array)
#3 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
#4 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('twentyfourhours...', Array, true)
#5 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('twentyfourhours...')
#6 /srv/users/craft/apps/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('twentyfourhours...')
#7 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
#8 /srv/users/craft/apps/craft/storage/runtime/compiled_templates/db/dbbf2adde7351591045c2d18b3c4c383f1351fc842f470704cdcaf665d945ddd.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
#9 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8c7b61297d009dd5f97c71a175c31de23ec89891531a3c93d4929e73d239ca3e->doDisplay(Array, Array)
#10 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#12 /srv/users/craft/apps/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /srv/users/craft/apps/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('comments-work/s...', Array)
#15 /srv/users/craft/apps/craft/vendor/twentyfourhoursmedia/comments-work/src/CommentsWork.php(205): craft\web\View->renderTemplate('comments-work/s...', Array)
#16 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/base/Plugin.php(217): twentyfourhoursmedia\commentswork\CommentsWork->settingsHtml()
#17 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
#18 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('comments-work', Object(twentyfourhoursmedia\commentswork\CommentsWork))
#19 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#21 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
#22 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
#23 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
#24 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
#25 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#26 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /srv/users/craft/apps/craft/public/index.php(22): yii\base\Application->run()
#28 {main}

**Comment by axelhebenstreit** [comment]
uninstalling and reinstalling did the trick :-)

> Am 03.02.2021 um 17:56 schrieb Axel Hebenstreit <info@axel.media>:
> 
>> Should be fixed by now
>> 
> 
> I’m afraid not – just updated to 1.2.1 and i get this:
> 
> 
> ReflectionException: Class twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset does not exist in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php:508
> Stack trace:
> #0 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(508): ReflectionClass->__construct('twentyfourhours...')
> #1 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('twentyfourhours...')
> #2 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('twentyfourhours...', Array, Array)
> #3 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('twentyfourhours...', Array, Array)
> #4 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
> #5 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('twentyfourhours...', Array, true)
> #6 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('twentyfourhours...')
> #7 /srv/users/craft/apps/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('twentyfourhours...')
> #8 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
> #9 /srv/users/craft/apps/craft/storage/runtime/compiled_templates/db/dbbf2adde7351591045c2d18b3c4c383f1351fc842f470704cdcaf665d945ddd.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
> #10 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8c7b61297d009dd5f97c71a175c31de23ec89891531a3c93d4929e73d239ca3e->doDisplay(Array, Array)
> #11 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
> #12 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
> #13 /srv/users/craft/apps/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
> #14 /srv/users/craft/apps/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
> #15 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('comments-work/s...', Array)
> #16 /srv/users/craft/apps/craft/vendor/twentyfourhoursmedia/comments-work/src/CommentsWork.php(205): craft\web\View->renderTemplate('comments-work/s...', Array)
> #17 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/base/Plugin.php(217): twentyfourhoursmedia\commentswork\CommentsWork->settingsHtml()
> #18 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
> #19 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('comments-work', Object(twentyfourhoursmedia\commentswork\CommentsWork))
> #20 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> #21 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
> #22 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
> #23 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
> #24 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
> #25 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
> #26 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
> #27 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
> #28 /srv/users/craft/apps/craft/public/index.php(22): yii\base\Application->run()
> #29 {main}
> 
> Next yii\di\NotInstantiableException: Failed to instantiate component or class "twentyfourhoursmedia\commentswork\assetbundles\commentswork\CommentsWorkAsset". in /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php:510
> Stack trace:
> #0 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(386): yii\di\Container->getDependencies('twentyfourhours...')
> #1 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('twentyfourhours...', Array, Array)
> #2 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('twentyfourhours...', Array, Array)
> #3 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject(Array)
> #4 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle('twentyfourhours...', Array, true)
> #5 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/View.php(287): yii\web\AssetManager->getBundle('twentyfourhours...')
> #6 /srv/users/craft/apps/craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): yii\web\View->registerAssetBundle('twentyfourhours...')
> #7 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method', false, false)
> #8 /srv/users/craft/apps/craft/storage/runtime/compiled_templates/db/dbbf2adde7351591045c2d18b3c4c383f1351fc842f470704cdcaf665d945ddd.php(46): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\web\View), 'registerAssetBu...', Array, 'method')
> #9 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8c7b61297d009dd5f97c71a175c31de23ec89891531a3c93d4929e73d239ca3e->doDisplay(Array, Array)
> #10 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
> #11 /srv/users/craft/apps/craft/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
> #12 /srv/users/craft/apps/craft/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
> #13 /srv/users/craft/apps/craft/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
> #14 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('comments-work/s...', Array)
> #15 /srv/users/craft/apps/craft/vendor/twentyfourhoursmedia/comments-work/src/CommentsWork.php(205): craft\web\View->renderTemplate('comments-work/s...', Array)
> #16 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/base/Plugin.php(217): twentyfourhoursmedia\commentswork\CommentsWork->settingsHtml()
> #17 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/controllers/PluginsController.php(114): craft\base\Plugin->getSettingsResponse()
> #18 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('comments-work', Object(twentyfourhoursmedia\commentswork\CommentsWork))
> #19 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> #20 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
> #21 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit-plugin-set...', Array)
> #22 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit-plugin-set...', Array)
> #23 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('plugins/edit-pl...', Array)
> #24 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('plugins/edit-pl...', Array)
> #25 /srv/users/craft/apps/craft/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
> #26 /srv/users/craft/apps/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
> #27 /srv/users/craft/apps/craft/public/index.php(22): yii\base\Application->run()
> #28 {main}
>

**Comment by 24hoursmedia-craftcms** [comment]
Thank you for your feedback!
We had to set up a case sensitive volume to reproduce and test, and will work further that way.
Uninstalling shouldn't have been necessary when updating to 1.2.2.
